mkdir build
cd build
cmake .. -DOPT_BUILD_HACKRF_SOURCE=OFF \
  -DOPT_BUILD_HERMES_SOURCE=OFF \
  -DOPT_BUILD_PLUTOSDR_SOURCE=OFF \
  -DOPT_BUILD_RFSPACE_SOURCE=OFF \
  -DOPT_BUILD_METEOR_DEMODULATOR=OFF \
  -DOPT_BUILD_NEW_PORTAUDIO_SINK=ON \
  -DOPT_BUILD_AUDIO_SINK=OFF
make -j12