#!/bin/sh
cmake .. \
  -DOPT_BUILD_AUDIO_SINK=OFF \
  -DOPT_BUILD_BLADERF_SOURCE=OFF \
  -DOPT_BUILD_HACKRF_SOURCE=OFF \
  -DOPT_BUILD_HERMES_SOURCE=OFF \
  -DOPT_BUILD_M17_DECODER=OFF \
  -DOPT_BUILD_METEOR_DEMODULATOR=OFF \
  -DOPT_BUILD_NEW_PORTAUDIO_SINK=ON \
  -DOPT_BUILD_PLUTOSDR_SOURCE=OFF \
  -DOPT_BUILD_PORTAUDIO_SINK=ON \
  -DOPT_BUILD_RFSPACE_SOURCE=OFF \
  -DOPT_BUILD_SOAPY_SOURCE=ON \
  -DOPT_BUILD_SDRPLAY_SOURCE=OFF \
  -DOPT_BUILD_SPECTRAN_HTTP_SOURCE=OFF
